workflows:
  ios-build:
    name: iOS Build Workflow
    max_build_duration: 60
    environment:
      xcode: 15.0
      cocoapods: default
      vars:
        FLUTTER_VERSION: stable
    scripts:
      - name: Install Flutter
        script: |
          git clone https://github.com/flutter/flutter.git -b $FLUTTER_VERSION
          export PATH="$PATH:`pwd`/flutter/bin"

      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Clean project
        script: |
          flutter clean

      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install
          cd ..

      - name: Build iOS .ipa (no codesign)
        script: |
          flutter build ipa --no-codesign

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/ipa/*.dSYM.zip
      - flutter_drive.log
