name: tunue_collection
description: Un'app per il collezionismo di carte Tunuè

# La versione segue il pattern [major].[minor].[patch]+[build]
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  
  # Gestione stato
  provider: ^6.0.5
  
  # Localizzazione e formattazione
  intl: ^0.19.0
  
  # Persistenza dati
  shared_preferences: ^2.1.0
  
  # Utilità
  path_provider: ^2.0.14
  uuid: ^3.0.7
  supabase_flutter: ^2.3.4
  flutter_fortune_wheel: ^1.3.2
  webview_flutter: ^4.0.0
  http: ^1.1.0
  video_player: ^2.8.1
  model_viewer_plus: 1.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  # Risorse statiche
  assets:
    - assets/images/
    - assets/images/icons/
    - assets/images/icons/tunue_logo.png
    - assets/images/icons/svg/
    - assets/images/icons/png/
    - assets/images/logos/
    - assets/videos/
    - assets/models/
  
  # Fonts personalizzati
  fonts:
    - family: NeueHaasDisplay
      fonts:
        - asset: assets/fonts/NeueHaasDisplayRoman.ttf
          weight: 400
        - asset: assets/fonts/NeueHaasDisplayLight.ttf
          weight: 300
        - asset: assets/fonts/NeueHaasDisplayThin.ttf
          weight: 200
        - asset: assets/fonts/NeueHaasDisplayXThin.ttf
          weight: 100
        - asset: assets/fonts/NeueHaasDisplayXXThin.ttf
          weight: 100
        - asset: assets/fonts/NeueHaasDisplayMediu.ttf
          weight: 500
        - asset: assets/fonts/NeueHaasDisplayBold.ttf
          weight: 700
        - asset: assets/fonts/NeueHaasDisplayBlack.ttf
          weight: 900
        - asset: assets/fonts/NeueHaasDisplayRomanItalic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/NeueHaasDisplayLightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/NeueHaasDisplayThinItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/NeueHaasDisplayXThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/NeueHaasDisplayXXThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/NeueHaasDisplayMediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/NeueHaasDisplayBoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/NeueHaasDisplayBlackItalic.ttf
          weight: 900
          style: italic